// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnbgwcikocwspbsefavn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uYmd3Y2lrb2N3c3Bic2VmYXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTk0NTEsImV4cCI6MjA1ODc5NTQ1MX0.fFm7AEY9lYiTFPG8v9XKrIY3IPQnLBWNGbEo8CL89zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);